Specify grub target - remove unneeded backslash

diff --git a/autoinstaller-scripts/stage4-hetzner-cloud/stage4-hetzner-cloud b/autoinstaller-scripts/stage4-hetzner-cloud/stage4-hetzner-cloud
--- a/autoinstaller-scripts/stage4-hetzner-cloud/stage4-hetzner-cloud
+++ b/autoinstaller-scripts/stage4-hetzner-cloud/stage4-hetzner-cloud
@@ -123,7 +123,7 @@ rm -fr "${MOUNTPOINT}"/boot/*gentoo-dist* "${MOUNTPOINT}"/lib/modules/*gentoo-di
 export DISK="${DISK}"
 
 echo -ne "\n\nGRUB:\n"
-chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install $DISK' || die "Unable to run grub-install"
+chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install --target=i386-pc $DISK' || die "Unable to run grub-install"
 chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-mkconfig -o /boot/grub/grub.cfg' || die "Unable to run grub-mkconfig"
 chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" rc-update add net.eth0 default' > /dev/null 2>&1 || die "Unable to run rc-update"
 chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" echo "root:ChangeMe1999" | chpasswd' || die "Unable to run chpasswd"
@@ -135,6 +135,6 @@ then
 	cp "${INITIAL_PWD}"/id_rsa.pub root/.ssh/authorized_keys || die "Unable to copy authorized_keys"
 fi
 
-echo -ne "LSPCI -k:\n$( lspci -k | grep "Kernel\ driver" | sort | uniq )\n\nLSMOD:\n$( lsmod )\n" > "${MOUNTPOINT}"/root/.modules_info || die "Unable to write .modules_info"
+echo -ne "LSPCI -k:\n$( lspci -k | grep "Kernel driver" | sort | uniq )\n\nLSMOD:\n$( lsmod )\n" > "${MOUNTPOINT}"/root/.modules_info || die "Unable to write .modules_info"
 
 echo -ne "\n\n\nTHE STAGE4 INSTALLATION HAS BEEN COMPLETED....HAVE A NICE DAY ;)\n"
diff --git a/autoinstaller-scripts/stage4/stage4 b/autoinstaller-scripts/stage4/stage4
--- a/autoinstaller-scripts/stage4/stage4
+++ b/autoinstaller-scripts/stage4/stage4
@@ -125,7 +125,7 @@ then
 elif [ "${TYPE}" = "bios" ]
 then
 	sed '/EFI/d' -i etc/fstab || die "Unable to replace EFI in fstab"
-	chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install $DISK' || die "Unable to run grub-install"
+	chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install --target=i386-pc $DISK' || die "Unable to run grub-install"
 fi
 
 chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-mkconfig -o /boot/grub/grub.cfg' || die "Unable to run grub-mkconfig"
@@ -138,6 +138,6 @@ then
 	cp "${INITIAL_PWD}"/id_rsa.pub root/.ssh/authorized_keys || die "Unable to copy authorized_keys"
 fi
 
-echo -ne "LSPCI -k:\n$( lspci -k | grep "Kernel\ driver" | sort | uniq )\n\nLSMOD:\n$( lsmod )\n" > "${MOUNTPOINT}"/root/.modules_info || die "Unable to write .modules_info"
+echo -ne "LSPCI -k:\n$( lspci -k | grep "Kernel driver" | sort | uniq )\n\nLSMOD:\n$( lsmod )\n" > "${MOUNTPOINT}"/root/.modules_info || die "Unable to write .modules_info"
 
 echo -ne "\n\n\nTHE STAGE4 INSTALLATION HAS BEEN COMPLETED....HAVE A NICE DAY ;)\n"
